name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Environment Variables
        run: echo "NEXT_PUBLIC_USER_API=${{ secrets.NEXT_PUBLIC_USER_API }}" >> .env && echo "NEXT_PUBLIC_OPERATION_API=${{ secrets.NEXT_PUBLIC_OPERATION_API }}" >> .env && echo "NEXT_PUBLIC_RECORD_API=${{ secrets.NEXT_PUBLIC_RECORD_API }}" >> .env &&  echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env && echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
      - name: Build Docker
        run: docker build -t fernando0988/ntd_calculator-frontend .
      - name: Login docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p  ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Image to Docker
        run: docker push fernando0988/ntd_calculator-frontend:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull fernando0988/ntd_calculator-frontend:latest
      - name: Delete Container
        run: docker rm -f nextjs-ntd_calculator-frontend-container
      - name: Run Container
        run: docker run -d -p 3000:3000 --name nextjs-ntd_calculator-frontend-container fernando0988/ntd_calculator-frontend:latest

